### ISSUE TITLE
Possible problem with the new JCE Editor

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSEmbed#1]
"seems to be a problem with the JCE editor.... The new version doesn't seem to have a allow IFrame option....."

![jce 3](https://cloud.githubusercontent.com/assets/3868028/12079402/f11e7662-b205-11e5-8cc4-61120ab32883.jpg)
![jce 2](https://cloud.githubusercontent.com/assets/3868028/12079403/f11f31b0-b205-11e5-8dbe-3597e84b7790.jpg)
![jce 1](https://cloud.githubusercontent.com/assets/3868028/12079401/f11dcfe6-b205-11e5-8b4b-9b0c17c6477c.jpg)

**Comment by andergmartins** [comment]
Just updated the documentation. Please check: https://www.alledia.com/docs/osembed/start/#jce

**Comment by htmgarcia** [comment]
Ah, I see.

**Comment by htmgarcia** [comment]
Thanks @andergmartins ! :)
