### ISSUE TITLE
JInstaller: :Install: Can't find XML setup file.

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSEmbed#2]
Had 2 reports of this now ...

i keep getting this message when i try to install OSEmbed. im running the latest version of Joomla! 3.4.8

Warning

JInstaller: :Install: Can't find XML setup file.

Error

Unable to find install package

**Comment by htmgarcia** [comment]
A new report: https://www.alledia.com/forum/osembed/308-installer-failed-twice/

**Comment by andergmartins** [comment]
Fixed. It was an issue in the Jenkins job, which corrupted the built package

**Comment by htmgarcia** [comment]
Thanks @andergmartins !
