### ISSUE TITLE
Embed Twitter streams and Facebook streams

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSEmbed#8]
How about embedding the latest 5 twitter posts or Facebook posts?

**Comment by htmgarcia** [comment]
That would require the user get API keys

**Comment by andergmartins** [comment]
+1
We can add a param in the plugin to set those keys, just will need to make sure we can get all the information we need from the URL

**Comment by stevejburge** [comment]
I think this is a good idea. One of the best things we could add.

**Comment by andergmartins** [comment]
Closing here. Will continue on the pro repo
